name = "JSON3"
uuid = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "0.1.5"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[compat]
Parsers = "0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[targets]
test = ["Test", "UUIDs"]

